name:                papertrails
version:             0.1.0.0
github:              "dustin/papertrails"
license:             BSD3
author:              "Dustin Sallings"
maintainer:          "dustin@spy.net"
copyright:           "MIT"

extra-source-files:
- README.markdown

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/dustin/papertrails#readme>

dependencies:
- base >= 4.7 && < 5
- amazonka >= 2.0
- amazonka-core >= 2.0
- amazonka-s3 >= 2.0
- generic-lens
- lens
- conduit
- conduit-extra
- zlib-conduit
- bytestring
- text
- time
- process
- directory
- resourcet
- optparse-applicative

executables:
  papertrails:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -Wall
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
