packages:
- .
extra-deps:
- zlib-conduit-1.1.0@sha256:a5e5ae6ad61038d1420175267b34252c1ba79748c21ab6f031dc2a42eb820188
- github: brendanhay/amazonka
  commit: e64638ae16dc6d549d6e7c21262245e29761ede7
  subdirs:
  - lib/amazonka
  - lib/amazonka-core
  - lib/services/amazonka-s3
  - lib/services/amazonka-sts

resolver: lts-19.21


nix:
  packages: [zlib]
